---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tarotfab/public_html/
    - /bin/cp assets $DEPLOYPATH
    - /bin/cp images $DEPLOYPATH
    - /bin/cp scripts $DEPLOYPATH
    - /bin/cp styles $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH
    # - /bin/cp modal-style.css $DEPLOYPATH
    # - /bin/cp main.js $DEPLOYPATH